#spring.data.mongodb.database=${MONGO_DATABASE}
#spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
#management.security.enabled = false
spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
